<?php $this->layout()->setLayout('page'); ?>

<h2>Current Menus</h2>
<?php if ($this->menus != null) { ?>
<table>
	<thead>
		<tr>
			<th>Links</th>
			<th>Menu Name</th>
			<th>Page Name</th>
			<th>Link</th>
			<th>Access</th>
		</tr>
	</thead>
	<tbody>
		<?php echo $this->partialLoop('partials/_menu-row.phtml', $this->menus); ?>
	</tbody>
</table>
<?php } else { ?>
<p>You do not have any menus yet.</p>
<?php } ?>
<p><a href="/menu/create">Create a new menu</a></p>
