<?php $this->layout()->setLayout('page'); ?>

<h3><?php echo $this->translate('Current Menus'); ?></h3>
<?php if ($this->menus != null) { ?>
<table>
	<thead>
		<tr>
			<th><?php echo $this->translate('Links'); ?></th>
			<th><?php echo $this->translate('Menu Name'); ?></th>
			<th><?php echo $this->translate('Page Name'); ?></th>
			<th><?php echo $this->translate('Link'); ?></th>
			<th><?php echo $this->translate('Access'); ?></th>
		</tr>
	</thead>
	<tbody>
		<?php echo $this->partialLoop('partials/_menu-row.phtml', $this->menus); ?>
	</tbody>
</table>
<?php } else { ?>
<p><?php echo $this->translate('You do not have any menus yet.'); ?></p>
<?php } ?>
<p><a href="<?php echo $this->translate('/en_US');?>/default/menu/create">
	<?php echo $this->translate('Create a new menu'); ?></a></p>
