<?php $this->layout()->setLayout('page'); ?>

<?php
	$confirmMessage = $this->translate('Are you sure to delete?');
?>

<table>
	<thead>
		<tr>
			<th><?php echo $this->translate('ID') ?></th>
			<th><?php echo $this->translate('Name') ?></th>
			<th><?php echo $this->translate('Field') ?></th>
			<th><?php echo $this->translate('Contact No. #1') ?></th>
			<th><?php echo $this->translate('Contact No. #2') ?></th>
			<th><?php echo $this->translate('Address') ?></th>
			<th><?php echo $this->translate('Links') ?></th>
		</tr>
	</thead>
	<tbody>
<?php foreach ($this->companies as $company): ?>
		<tr>
			<td>
				<?php echo $company['id']; ?>
			</td>
			<td>
				<?php echo $company['name']; ?>
			</td>
			<td>
				<?php echo $company['field']; ?>
			</td>
			<td>
				<?php echo $company['contact_number_1']; ?>
			</td>
			<td>
				<?php echo $company['contact_number_2']; ?>
			</td>
			<td>
				<?php echo $company['address']; ?>
			</td>
			<td>
				<a href="<?php echo $this->translate('/en_US');?>/sms/company/delete/id/<?php echo $company['id']; ?>" 
					onclick="return confirm('<?php echo $confirmMessage; ?>')"><?php echo $this->translate('Delete') ?></a>
				<br/>
				<a href="<?php echo $this->translate('/en_US');?>/sms/company/update/id/<?php echo $company['id']; ?>">
					<?php echo $this->translate('Update') ?></a>
			</td>
		</tr>
<?php endforeach; ?>
	</tbody>
</table>

<p><a href="<?php echo $this->translate('/en_US'); ?>
	/sms/company/create"><?php echo $this->translate('Create a new company'); ?></a></p>