<?php $this->layout()->setLayout('page'); ?>

<h3><?php echo $this->translate('Bugs'); ?></h3>
<p><?php echo $this->translate('If you find a bug please'); ?> 
		<a href="<?php echo $this->translate('/en_US'); ?>/default/bug/create">
			<?php echo $this->translate('click here'); ?></a>.</p>
<p><?php echo $this->translate('If you are an admin and want to mange bugs');?> 
	<a href="<?php echo $this->translate('/en_US'); ?>/default/bug/list">
		<?php echo $this->translate('click here'); ?></a>.</p>
