<?php $this->layout()->setLayout('page'); ?>

<h3><?php echo $this->translate('Current Bugs'); ?></h3>
<?php echo $this->listToolsForm; ?>

<p>
<?php 
	echo $this->paginationControl($this->paginator,
		'Sliding',
		'partials/pagination-control.phtml'); 
?>
</p>

<table>
	<thead>
		<tr>
			<th>&nbsp;</th>
			<th><?php echo $this->translate('ID'); ?></th>
			<th><?php echo $this->translate('Date'); ?></th>
			<th><?php echo $this->translate('Priority'); ?></th>
			<th><?php echo $this->translate('Status'); ?></th>
			<th><?php echo $this->translate('URL'); ?></th>
			<th><?php echo $this->translate('Submitter'); ?></th>
			<th><?php echo $this->translate('Description'); ?></th>
		</tr>
	</thead>
	<tbody>
		<?php echo $this->partialLoop('bug/table-row.phtml', $this->paginator); ?>
	</tbody>
</table>
