<?php $confirmMessage = $this->translate('Are you sure to delete?'); ?>

<tr>
	<td><a href="<?php echo $this->translate('/en_US'); ?>
		/default/bug/edit/id/<?php echo $this->id; ?>">
			<?php echo $this->translate('Update'); ?></a> | 
		<a href="<?php echo $this->translate('/en_US'); ?>
		/default/bug/delete/id/<?php echo $this->id; ?>" 
			onclick="return confirm('<?php echo $confirmMessage; ?>')">
			<?php echo $this->translate('Delete'); ?></a></td>
	<td><?php echo $this->id; ?></td>
	<td><?php echo date('m/d/y', $this->date); ?></td>
	<td><?php echo $this->priority; ?></td>
	<td><?php echo $this->status; ?></td>
	<td><?php echo $this->url; ?></td>
	<td><?php echo $this->author; ?></td>
	<td><?php echo $this->description; ?></td>
</tr>
