<?php $this->layout()->setLayout('page'); ?>

<h3>Featured Content</h3>
<?php
if ($this->featuredItems)
{
	foreach ($this->featuredItems as $page)
	{
		?>
		<h4><a href="/page/open/id/<?php echo $page->id; ?>">
			<?php echo $page->headline; ?>
		</a></h4>
		<img src="<?php echo $page->image; ?>" alt="<?php echo $page->headline; ?>" />
		<p><?php echo $page->description; ?></p>
		<br style="clear:left;" />
		<?php
	}
}

if ($this->recentPages) { ?>
	<h4>More Pages</h4>
	<ul>
	<?php foreach ($this->recentPages as $page) { ?>
	<li><a href="/page/open/id/<?php echo $page->id; ?>">
		<?php echo $page->headline; ?>
	</a></li>
	<?php } ?>
	</ul>
<?php } ?>
