<?php $this->layout()->setLayout('page'); ?>

<h3><?php echo $this->translate('Last Content'); ?></h3>
<?php
if ($this->featuredItems)
{
	foreach ($this->featuredItems as $page)
	{
		?>
		<h3><a href="<?php echo $this->translate('/en_US'); ?>/pages/<?php echo $page->id; ?>">
			<?php echo $page->headline; ?>
		</a></h3>
		<img src="<?php echo $page->image; ?>" alt="<?php echo $page->headline; ?>" />
		<p><?php echo $page->description; ?></p>
		<br style="clear:left;" />
		<?php
	}
}

if ($this->recentPages) { ?>
	<h4><?php echo $this->translate('More Pages'); ?></h4>
	<ul>
	<?php foreach ($this->recentPages as $page) { ?>
	<li><a href="<?php echo $this->translate('/en_US'); ?>/pages/<?php echo $page->id; ?>">
		<?php echo $page->headline; ?>
	</a></li>
	<?php } ?>
	</ul>
<?php } ?>
