<?php $this->layout()->setLayout('page'); ?>

<h3><?php echo $this->translate('Current Pages'); ?></h3>
<?php
	if ($this->pages != null)
	{
?>
<table>
	<thead>
		<tr>
			<th><?php echo $this->translate('Links'); ?></th>
			<th><?php echo $this->translate('Name'); ?></th>
		<tr>
	</thead>
	<tbody>
		<?php echo $this->partialLoop('partials/_page-row.phtml', $this->pages); ?>
	</tbody>
</table>
<?php 
	}
	else
	{
?>
<p><?php echo $this->translate('You do not have any pages yet.'); ?></p>
<?php
	}
?>
<p><a href="<?php echo $this->translate('/en_US'); ?>/default/page/create">
	<?php echo $this->translate('Create a new page'); ?></a></p>

