<h3>Welcome to Melobit Installation</h3>
<hr />
<h3>[Step 2]</h3>
<?php
 if ($this->error == null) 
 {
 	echo '<p>Your database was successfully installed with this name: <strong>' . $this->dbName . '</strong></p>';
 	echo '<p><a href="'; 
 	echo $this->translate('/en_US');
 	echo '/default/installer/tables">Next Step</a> (create tables)</p>';
 }
 else
 {
 	echo '<p>An error has been occured:</p>';
 	echo $this->error;
 }
?>
