<h3>Welcome to Melobit Installation</h3>
<hr />
<h3>[Step 1]</h3>
<p>To start, please follow these steps:</p>
<ol>
	<li>Create an empty database.</li>
	<li>Open database.ini file which is in /application/configs/ path.</li>	
	<li>Fill requested information about your just created database.</li>
	<li>Click in the below link to check your database connection.</li>
</ol>
<p><a href="<?php echo $this->translate('/en_US'); ?>
	/default/installer/database">Next Step</a> (check database connection)</p>
