<?php $this->layout()->setLayout('page'); ?>

<h3><?php echo $this->translate('List of Customers'); ?></h3><br />

<?php if (!$this->customers): ?>
<p>There is no customer!</p>
<?php else: ?>

<?php
	$confirmMessage = $this->translate('Are you sure to delete?');
?>

<table>
	<thead>
		<tr>
			<th><?php echo $this->translate('ID') ?></th>
			<th><?php echo $this->translate('First Name') ?></th>
			<th><?php echo $this->translate('Last Name') ?></th>
			<th><?php echo $this->translate('Company Name') ?></th>
			<th><?php echo $this->translate('Contact No. #1') ?></th>
			<th><?php echo $this->translate('Contact No. #2') ?></th>
			<th><?php echo $this->translate('Address') ?></th>
			<th><?php echo $this->translate('Links') ?></th>
		</tr>
	</thead>
	<tbody>
<?php foreach ($this->customers as $customers): ?>
		<tr>
			<td>
				<?php echo $customers['id']; ?>
			</td>
			<td>
				<?php echo $customers['first_name']; ?>
			</td>
			<td>
				<?php echo $customers['last_name']; ?>
			</td>
			<td>
				<?php $companyName = Sms_Model_CompanyModel::listCompany($customers['company_id']); ?>
				<?php echo $companyName['name']; ?>
			</td>
			<td>
				<?php echo $customers['contact_number_1']; ?>
			</td>
			<td>
				<?php echo $customers['contact_number_2']; ?>
			</td>
			<td>
				<?php echo $customers['address']; ?>
			</td>
			<td>
				<a href="<?php echo $this->translate('/en_US');?>/sms/customer/delete/id/<?php echo $customers['id']; ?>" 
					onclick="return confirm('<?php echo $confirmMessage; ?>')"><?php echo $this->translate('Delete') ?></a>
				<br/>
				<a href="<?php echo $this->translate('/en_US');?>/sms/customer/update/id/<?php echo $customers['id']; ?>">
					<?php echo $this->translate('Update') ?></a>
			</td>
		</tr>
<?php endforeach; ?>
	</tbody>
</table>

<?php endif; ?>

<p><a href="<?php echo $this->translate('/en_US'); ?>
	/sms/customer/create"><?php echo $this->translate('Create a new customer'); ?></a></p>
