<a href="
	  	<?php echo $this->url(array(
		'module' => 'default',
		'controller' => 'locale',
		'action' => 'index',
		'locale' => 'en_US'), 'default', true); ?>
"><img src="/images/locale/en_US.png" /></a>
<a href="
	  	<?php echo $this->url(array(
		'module' => 'default',
		'controller' => 'locale',
		'action' => 'index',
		'locale' => 'fa_IR'), 'default', true); ?>
"><img src="/images/locale/fa_IR.png" /></a>
