<?php $this->layout()->setLayout('page'); ?>

<?php
	$this->headLink()->appendStylesheet('/javascripts/JalaliJSCalendar-1.4/skins/calendar-blue.css');
	$this->headLink()->appendStylesheet('/javascripts/JalaliJSCalendar-1.4/skins/global.css');
	echo $this->headLink();
	$this->headScript()->appendFile('/javascripts/JalaliJSCalendar-1.4/jalali.js');
	$this->headScript()->appendFile('/javascripts/JalaliJSCalendar-1.4/calendar.js');
	$this->headScript()->appendFile('/javascripts/JalaliJSCalendar-1.4/lang/calendar-fa.js');
	$this->headScript()->appendFile('/javascripts/JalaliJSCalendar-1.4/calendar-setup.js');
	echo $this->headScript();
?>

<?php
	echo $this->form;
?>

<script type="text/javascript">
	// Calendar
	Calendar.setup({
		inputField				: "dispatch_date",	// id of the input field
		displayArea			: "dispatch_date", // id of displayArea field
		button						: "dispatchDateChooserImge",	// trigger for the calendar (button ID)
		ifFormat					: "%Y-%m-%d %H:%M",	// format of the input field
		showsTime				: true,
		dateType					: 'jalali',
		timeFormat				: "24",
		weekNumbers		: false,
        showOthers			: true,
		singleClick				: false,
		autoShowOnFocus	: false,
		langNumbers			: false,
	});
</script>