<?php $this->layout()->setLayout('page'); ?>

<?php
	// append necessary files
	$this->headLink()->appendStylesheet('/javascripts/JalaliJSCalendar-1.4/skins/calendar-blue.css');
	$this->headLink()->appendStylesheet('/javascripts/JalaliJSCalendar-1.4/skins/global.css');
	echo $this->headLink();
	$this->headScript()->appendFile('/javascripts/jQuery-plugins/jQuery-form.js');
	$this->headScript()->appendFile('/javascripts/jQuery-validationEngine-2.6.1/js/jquery-ui.min.js');
	$this->headScript()->appendFile('/javascripts/JalaliJSCalendar-1.4/jalali.js');
	$this->headScript()->appendFile('/javascripts/JalaliJSCalendar-1.4/calendar.js');
	$this->headScript()->appendFile('/javascripts/JalaliJSCalendar-1.4/lang/calendar-fa.js');
	$this->headScript()->appendFile('/javascripts/JalaliJSCalendar-1.4/calendar-setup.js');
	echo $this->headScript();
?>

<script type="text/javascript">
	jQuery(function($){
		// Calendar for start_date
		Calendar.setup({
			inputField				: "start_date",	// id of the input field
			displayArea			: "start_date", // id of displayArea field
			button					: "startDateChooserImge",	// trigger for the calendar (button ID)
			ifFormat					: "%Y-%m-%d %H:%M",	// format of the input field
			showsTime				: true,
			dateType				: 'jalali',
			timeFormat			: "24",
			weekNumbers		: false,
			showOthers			: true,
			singleClick				: false,
			autoShowOnFocus	: false,
			langNumbers			: false,
		});
		// Calendar for end_date
		Calendar.setup({
			inputField				: "end_date",	// id of the input field
			displayArea			: "end_date", // id of displayArea field
			button					: "endDateChooserImge",	// trigger for the calendar (button ID)
			ifFormat					: "%Y-%m-%d %H:%M",	// format of the input field
			showsTime				: true,
			dateType				: 'jalali',
			timeFormat			: "24",
			weekNumbers		: false,
			showOthers			: true,
			singleClick				: false,
			autoShowOnFocus	: false,
			langNumbers			: false,
		});
	});
</script>

<h3><?php echo $this->translate('List of Orders'); ?></h3><br />

<?php if (!$this->ordersArray): ?>
<p><?php echo $this->translate('There is no order!'); ?></p>
<?php else: ?>

<?php
	$confirmMessage = $this->translate('Are you sure to delete?');
?>

<table>
	<thead>
		<tr>
			<th><?php echo $this->translate('ID') ?></th>
			<th><?php echo $this->translate('Customer Name') ?></th>
			<th><?php echo $this->translate('Orderer Username') ?></th>
			<th><?php echo $this->translate('SMS Quantity') ?></th>
			<th><?php echo $this->translate('Order Date') ?></th>
			<!--<th><?php // echo $this->translate('SMS Content') ?></th>-->
			<!-- <th><?php // echo $this->translate('Test Phone') ?></th> -->
			<th><?php echo $this->translate('Order Status') ?></th>
			<th><?php echo $this->translate('Control Status') ?></th>
			<th><?php echo $this->translate('Dispatch Status') ?></th>
			<th><?php echo $this->translate('Links') ?></th>
		</tr>
	</thead>
	<tbody>
<?php foreach ($this->ordersArray as $order): ?>
		<tr>
			<td>
				<?php echo $order['id']; ?>
			</td>
			<td>
				<?php $customerName = Sms_Model_CustomerModel::listCustomer($order['customer_id']);?>
				<?php echo $customerName['first_name'] . ' ' .  $customerName['last_name']; ?>
			</td>
			<td>
				<?php $ordererUsername = Model_UserModel::getUsers($order['user_id']);?>
				<?php echo $ordererUsername['username']; ?>
			</td>
			<td>
				<?php echo $order['sms_quantity']; ?>
			</td>
			<td>
				<?php echo Melobit_Date_Convertor::timestamp_to_jalali($order['order_date']); ?>
			</td>
			<!--
			<td>
				<?php // echo $order['sms_content']; ?>
			</td>
			<td>
				<?php // echo $order['test_phone']; ?>
			</td>
			-->
			<td>
				<?php echo $order['order_status']; ?>
			</td>
			<td>
				<?php echo $order['control_status']; ?>
			</td>
			<td>
				<?php echo $order['dispatch_status']; ?>
			</td>
			<td>
				<a href="<?php echo $this->translate('/en_US');?>/sms/order/list-destination/id/<?php echo $order['id']; ?>" >
					<?php echo $this->translate('Destination') ?></a>
				<br/>
				<a href="<?php echo $this->translate('/en_US');?>/sms/order/list-transaction/id/<?php echo $order['id']; ?>" >
					<?php echo $this->translate('Transaction') ?></a>
				<br/>
				<a href="<?php echo $this->translate('/en_US');?>/sms/order/update-order/id/<?php echo $order['id']; ?>">
					<?php echo $this->translate('Update') ?></a>
				<br/>
				<a href="<?php echo $this->translate('/en_US');?>/sms/order/review-order/id/<?php echo $order['id']; ?>">
					<?php echo $this->translate('Review') ?></a>
				<br/>
				<a href="<?php echo $this->translate('/en_US');?>/sms/order/delete-order/id/<?php echo $order['id']; ?>" 
					onclick="return confirm('<?php echo $confirmMessage; ?>')"><?php echo $this->translate('Delete') ?></a>
			</td>
		</tr>
<?php endforeach; ?>
	</tbody>
</table>
	<?php
		// Pagination control
		echo $this->paginationControl($this->ordersObject,
			'Sliding',
			'partials/pagination-control.phtml'); 
		?>
<?php endif; ?>

<?php
	// Order filter form
	echo $this->OrderFilterForm;
?>

<p><a href="<?php echo $this->translate('/en_US'); ?>
	/sms/order/create-order"><?php echo $this->translate('Create a new order'); ?></a></p>
	
