<?php $this->layout()->setLayout('blank'); ?>

<?php
	// append necessary files
	$this->headLink()->appendStylesheet('/javascripts/JalaliJSCalendar-1.4/skins/calendar-blue.css');
	$this->headLink()->appendStylesheet('/javascripts/JalaliJSCalendar-1.4/skins/global.css');
	echo $this->headLink();
	$this->headScript()->appendFile('/javascripts/jQuery-plugins/jQuery-form.js');
	$this->headScript()->appendFile('/javascripts/jQuery-validationEngine-2.6.1/js/jquery-ui.min.js');
	$this->headScript()->appendFile('/javascripts/JalaliJSCalendar-1.4/jalali.js');
	$this->headScript()->appendFile('/javascripts/JalaliJSCalendar-1.4/calendar.js');
	$this->headScript()->appendFile('/javascripts/JalaliJSCalendar-1.4/lang/calendar-fa.js');
	$this->headScript()->appendFile('/javascripts/JalaliJSCalendar-1.4/calendar-setup.js');
	echo $this->headScript();
?>

<!----- Review HTML Start ----->
<div class="six columns">
	<div class="panel" style="height:330px">
		<h4 class="hide-for-small"><?php echo $this->translate('SMS Content'); ?><hr></h4>
		<h5 class="subheader"><?php echo $this->order['sms_content'] ?></h5>
	</div>
</div>

	<?php 
		// Calculate destinations fee and quantity
		$totalDestinationsQuantity = 0;
		if ($this->destinations)
		{
			foreach ($this->destinations as $destinations)
			{
				$totalDestinationsQuantity += $destinations['destination_end'] - $destinations['destination_start'] +1;
			}
		}
		$totalDestinationsFeeWithoutTax = $totalDestinationsQuantity * $this->order['sms_quantity'] * $this->order['sms_fee'];
		$totalDestinationsFeeWithTax = ($totalDestinationsQuantity * $this->order['sms_quantity'] * $this->order['sms_fee']) * 1.05;

		// Calculate transactions fee
		$totalTransactionsFee = 0;
		if ($this->transactions)
		{
			foreach ($this->transactions as $transactions)
			{
				$totalTransactionsFee += $transactions['deposit_fee'];
			}
		}
		

	?>
	
<div class="six columns">
	<div class="panel" style="height:330px">
		<h4 class="hide-for-small"><?php echo $this->translate('Order Details'); ?><hr></h4>
		<span class="subheader"><?php echo $this->translate('Sender Company:'); ?></span>
			<?php $companyName = Sms_Model_CustomerModel::getCompanyNameByCustomerId($this->order['customer_id']);?>
			<?php echo $companyName['name']; ?>
			<br/>
		<span class="subheader"><?php echo $this->translate('Sender Customer:'); ?></span>
			<?php $customerName = Sms_Model_CustomerModel::listCustomer($this->order['customer_id']);?>
			<?php echo $customerName['first_name'] . ' ' .  $customerName['last_name']; ?>
			<br/>
		<span class="subheader"><?php echo $this->translate('Order Date:'); ?></span>
			<?php echo Melobit_Date_Convertor::timestamp_to_jalali($this->order['order_date']); ?>
			<br/>
		<span class="subheader"><?php echo $this->translate('Test Phone:'); ?></span>
			<?php echo $this->order['test_phone']; ?>
			<br/>
		<span class="subheader"><?php echo $this->translate('SMS Fee:'); ?></span>
			<span  id="smsFee"><?php echo $this->order['sms_fee']; ?></span>
			<br/>
		<span class="subheader"><?php echo $this->translate('SMS Quantity:'); ?></span>
			<span id="smsQuantity"><?php echo $this->order['sms_quantity']; ?></span>
			<br/>
		<span class="subheader"><?php echo $this->translate('SMS Destinations Quantity:'); ?></span>
			<span id="smsDestinationsQuantity"><?php echo $totalDestinationsQuantity; ?></span>
			<br/>			
		<span class="subheader"><?php echo $this->translate('Total Destinations Fee (without Tax):'); ?></span>
			<span id="totalDestinationsFeeWithoutTax"><?php echo $totalDestinationsFeeWithoutTax; ?></span>
			<br/>
		<span class="subheader"><?php echo $this->translate('Total Destinations Fee (with Tax):'); ?></span>
			<span id="totalDestinationsFeeWithTax"><?php echo $totalDestinationsFeeWithTax; ?></span>
			<br/>
		<span class="subheader"><?php echo $this->translate('Total Transaction Fee:'); ?></span>
			<span id="totalTransactionsFee"><?php echo $totalTransactionsFee; ?></span>
			<br/>
			
			<?php if ($this->order['order_status']): ?>
			
				<span class="subheader">
					<?php echo $this->translate('Order Status:'); ?>
				</span>
					<?php echo $this->translate('Confirmed!'); ?><br/>
				<a class="radius button alert <?php echo $this->translate('right'); ?>" 
					href="<?php echo $this->translate('/en_US'); ?>
					/sms/order/suspend-order/id/<?php echo $this->order['id']; ?>"><?php echo $this->translate('Suspend'); ?></a>			
					
			<?php else: ?>
			
				<span class="subheader">
					<?php echo $this->translate('Order Status:'); ?>
				</span>
					<?php echo $this->translate('Ready to confirm!'); ?><br/>
				<a class="radius button success <?php echo $this->translate('right'); ?>"
					onclick="return compareDestinationAndTransactionFee()"
					href="<?php echo $this->translate('/en_US'); ?>
					/sms/order/confirm-order/id/<?php echo $this->order['id']; ?>"><?php echo $this->translate('Confirm'); ?></a>
					
			<?php endif; ?>
		
	</div>
</div>
<!----- Review HTML End ----->

<!----- Review JavaScript Start ----->
<script type="text/javascript">
	// Compare destinations and transactions fee
	function compareDestinationAndTransactionFee()
	{
		var destinationsFee = parseFloat(jQuery("span#totalDestinationsFeeWithTax").text());
		var transactionsFee = parseFloat(jQuery("span#totalTransactionsFee").text());

		if (destinationsFee <= transactionsFee)
		{
				return true;
		}
		else
		{
			alert("<?php echo $this->translate('Your destinations fee is not equal to transactions fee!'); ?>");
			return false;
		}
	}
</script>
<!----- Review JavaScript End ----->

<!----- Destination HTML Start ----->
<div class="twelve columns">
	<div class="panel" style="">
		<h4 class="hide-for-small"><?php echo $this->translate('Destination'); ?><hr></h4>
		
		<!----- Destination List Start ----->	
		<?php
			$confirmMessage = $this->translate('Are you sure to delete?');
			$language = $this->translate('/en_US');
			$deleteLink = $this->translate('/en_US') . "/sms/order/delete-destination/id/";
			$updateLink = $this->translate('/en_US') . "/sms/order/update-destination/id/";
		?>

		<table>
			<thead>
				<tr>
					<th><?php echo $this->translate('ID') ?></th>
					<th><?php echo $this->translate('Order ID') ?></th>
					<th><?php echo $this->translate('Destination Type') ?></th>
					<th><?php echo $this->translate('Destination Value') ?></th>
					<th><?php echo $this->translate('Dispatch Date') ?></th>
					<th><?php echo $this->translate('Quantity') ?></th>
					<th><?php echo $this->translate('Requested') ?></th>
					<?php if (!$this->order['order_status']): ?>
						<th><?php echo $this->translate('Links') ?></th>
					<?php endif; ?>
				</tr>
			</thead>
			<tbody id="destinationTableBody">
		<?php if ($this->destinations): ?>
		<?php foreach ($this->destinations as $destinations): ?>
				<tr>
					<td>
						<?php echo $destinations['id']; ?>
					</td>
					<td>
						<?php echo $destinations['order_id']; ?>
					</td>
					<td>
						<?php echo $destinations['destination_type']; ?>
					</td>
					<td>
						<?php echo $destinations['destination_value']; ?>
					</td>
					<td>	
						<?php echo Melobit_Date_Convertor::timestamp_to_jalali($destinations['dispatch_date']); ?>
					</td>
					<td>
						<?php echo $destinations['destinations_quantity']; ?>
					</td>
					<td>
						<?php echo $destinations['destination_end'] - $destinations['destination_start'] +1; ?>
					</td>
					<?php if (!$this->order['order_status']): ?>
						<td>
							<a href="<?php echo $updateLink .  $destinations['id']; ?>">
								<img src="/images/misc/edit-icon-white-micro.png" style="margin: 0 10px; vertical-align: middle"></img>
							</a>
							<br/>
							<a href="<?php echo $deleteLink .  $destinations['id']; ?>" 
								onclick="return confirm('<?php echo $confirmMessage; ?>')">
								<img src="/images/misc/delete-icon-white-micro.png" style="margin: 0 10px; vertical-align: middle"></img>
							</a>
						</td>
					<?php endif; ?>
				</tr>
		<?php endforeach; ?>
		<?php endif; ?>
			</tbody>
		</table>
		<!----- Destination List End -----> 

		<!----- Destination Form Start -----> 
		<?php if (!$this->order['order_status']): ?>
		<div class="panel">
			<div style="margin:10px 0 10px 10px">
				<img src="/images/misc/plus-icon-green-small.png" style="margin: 0 10px; vertical-align: middle">
					<a href="#" id="destinationFormToggle" style="vertical-align: middle"><?php echo $this->translate('Create a new destination'); ?></a>
				</img>
			</div>
			<?php echo $this->destinationForm; ?>
		</div>
		<?php endif; ?>
		<!----- Destination Form End -----> 
		
	</div>
</div>
<!----- Destination HTML End ----->

<!----- Destination JavaScript Start ----->
<?php if (!$this->order['order_status']): ?>
<script type="text/javascript">
	// Calendar
	Calendar.setup({
		inputField				: "dispatch_date",	// id of the input field
		displayArea			: "dispatch_date", // id of displayArea field
		button						: "dispatchDateChooserImge",	// trigger for the calendar (button ID)
		ifFormat					: "%Y-%m-%d %H:%M",	// format of the input field
		showsTime				: true,
		dateType					: 'jalali',
		timeFormat				: "24",
		weekNumbers		: false,
        showOthers			: true,
		singleClick				: false,
		autoShowOnFocus	: false,
		langNumbers			: false,
	});
</script>
<?php endif; ?>

<script type="text/javascript">
	// Default destination city and range to hide
	jQuery("dt#destination_province-label, dt#destination_range-label, dd#destination_province-element, dd#destination_range-element")
		.css("display", "none");
	
	// Toggle destination city and range visibility
	jQuery(function($){
		jQuery("select#destination_type").bind("change", function(){
			var destinationType = jQuery(this).val();
			if (destinationType == 'province')
			{
				// And create city list depends on selected province if not exists
				if (!jQuery("select#destination_city").length)
				{
					var selectedProvinceId = jQuery("select#destination_province").val();
					var selectedRange = jQuery("select#destination_range").val();
					jQuery.ajax({
						type: "GET",
						url: "/en_US/sms/order/ajax-retrieve-city-list/province/" + selectedProvinceId + "/range/" + selectedRange,
						success: function(data){
							var destinationCityOptionsJson = data;
							var destinationCityOptionsHtml = '<select id="destination_city" name="destination_city">\n';
							$.each(destinationCityOptionsJson, function(cityCode, cityName){
								destinationCityOptionsHtml += '\t<option label="' + cityName + '" value="' + cityCode + '">' + cityName + "</option>\n";
							});
							destinationCityOptionsHtml += "</select>\n<br/>\n";
							jQuery("dt#destination_province-label, dt#destination_range-label, dd#destination_province-element, dd#destination_range-element").toggle("slow");					
							jQuery(destinationCityOptionsHtml).insertAfter("select#destination_province");
							
							// Populate destination value according to city
							jQuery("input#destination_value").val($("select#destination_city").val());		
					
							// Update destination value after changing city
							jQuery("select#destination_city").bind("change", function(){
								jQuery("input#destination_value").val(jQuery(this).val());
							});							
						}
					});				
				}
				else
				{
					// Becuase cities information has been loaded, just show them
					jQuery("dt#destination_province-label, dt#destination_range-label, dd#destination_province-element, dd#destination_range-element")
						.toggle("slow");	

					// Populate destination value according to city
					jQuery("input#destination_value").val($("select#destination_city").val());		
				}		
			}
			else
			{
				// Close province fields if exist
				jQuery("dt#destination_province-label, dt#destination_range-label, dd#destination_province-element, dd#destination_range-element")
					.toggle("slow");
					
				// Clean destination value
				jQuery("input#destination_value").val('');
			}
		});

		// Update cites according to selected range
		jQuery("select#destination_range").bind("change", function(){
			if (jQuery("select#destination_city").length) { jQuery("select#destination_city").empty(); }
			var selectedProvinceId = jQuery("select#destination_province").val();
			var selectedRange = jQuery("select#destination_range").val();
			jQuery.ajax({
				type: "GET",
				url: "/en_US/sms/order/ajax-retrieve-city-list/province/" + selectedProvinceId + '/range/' + selectedRange,
				success: function(data){
					var destinationCityOptionsJson = data;
					var destinationCityOptionsHtml = '';
					$.each(destinationCityOptionsJson, function(cityCode, cityName){
						destinationCityOptionsHtml += '<option label="' + cityName + '" value="' + cityCode + '">' + cityName + "</option>\n";
					});
					// Append updated city list
					jQuery(destinationCityOptionsHtml).appendTo("select#destination_city");					
					// Populate destination value according to city
					jQuery("input#destination_value").val($("select#destination_city").val());					
				}
			});	
		});
		
		// Update cites according to selected province
		jQuery("select#destination_province").bind("change", function(){
			if (jQuery("select#destination_city").length) { jQuery("select#destination_city").empty(); }
			var selectedProvinceId = jQuery("select#destination_province").val();
			var selectedRange = jQuery("select#destination_range").val();
			jQuery.ajax({
				type: "GET",
				url: "/en_US/sms/order/ajax-retrieve-city-list/province/" + selectedProvinceId + '/range/' + selectedRange,
				success: function(data){
					var destinationCityOptionsJson = data;
					var destinationCityOptionsHtml = '';
					$.each(destinationCityOptionsJson, function(cityCode, cityName){
						destinationCityOptionsHtml += '<option label="' + cityName + '" value="' + cityCode + '">' + cityName + "</option>\n";
					});
					// Append updated city list
					jQuery(destinationCityOptionsHtml).appendTo("select#destination_city");					
					// Populate destination value according to city
					jQuery("input#destination_value").val($("select#destination_city").val());		
				}
			});	
		});
	});
	

	// Toggle destination form
	jQuery("form#destinationForm").css("display", "none");
	jQuery(function($){		
		jQuery("a#destinationFormToggle").bind("click", function(event){
			jQuery("form#destinationForm").toggle("slow");				
			// Prevent default action
			event.preventDefault();
		});
	});
	
	// Find potential destinations
	jQuery(function($){
		var calculatorIcon = "<img id='calculatorIcon' src='/images/misc/calculator-icon.png' class='textInputImage'></img>";
		var calculateResult = "<span id='calculateResult'></span>";
		jQuery(calculatorIcon).appendTo(jQuery("input#destination_value").parent());
		jQuery(calculateResult).appendTo(jQuery("input#destination_value").parent());
		jQuery("img#calculatorIcon").bind("click", function(event){
			var calculateCode = jQuery("input#destination_value").val();
			var calculateType = jQuery("select#destination_type").val();
			jQuery.ajax({
				type: "GET",
				url: "/en_US/sms/order/ajax-calculate-destinations/code/" + calculateCode + "/type/" + calculateType,
				success: function(data){
					var returnedResult = data;
					jQuery("span#calculateResult").text(returnedResult);
				}
			});			
		});
	});

	// Push new destination row
	function appendNewDataToDestinationTable(data)
	{
		var newTableRow = "<tr><td>" 
			+ data.id +"</td><td>"
			+ data.order_id +"</td><td>"
			+ data.destination_type +"</td><td>"
			+ data.destination_value +"</td><td>"
			+ data.dispatch_date +"</td><td>"
			+ data.destinations_quantity +"</td><td>"
			+ data.requested +"</td><td>"
			+ "<a href='<?php echo $updateLink ?>" + data.id + "'>"
			+ "<img src='/images/misc/edit-icon-white-micro.png' style='margin: 0 10px; vertical-align: middle'></img>"
			+ "</a>"
			+ "<br/>"
			+ "<a href='<?php echo $updateLink ?>" + data.id +  "'>"
			+ "<img src='/images/misc/delete-icon-white-micro.png' style='margin: 0 10px; vertical-align: middle'></img>"
			+ "</a>"
			+ "</td></tr>";		
		jQuery(newTableRow)
			.css({
			 "background":"#2BA6CB",
			 "display":"none"
			})
			.appendTo("tbody#destinationTableBody")
			.fadeIn("slow", function(){
				jQuery(this).css({
				    "display":""
				    });
				jQuery(this).animate({
				    backgroundColor:"#F9F9F9"
				    },
				    300,
				    function(){
				jQuery(this).css({
				    "background":""
				    });	
				});
			});  
	}

	// Push new total destination quantity
	function appendNewDestinationQuantity(data)
	{
		// Fetch current and new destination quantity
		var currentTotalDestinationQuantity = parseFloat(jQuery("span#smsDestinationsQuantity").text());
		var newTotalDestinationQuantity = currentTotalDestinationQuantity + parseFloat(data.requested);
		
		// Fire!
		jQuery("span#smsDestinationsQuantity").text(newTotalDestinationQuantity);
	}
	
	// Push new destinations fee (without tax)
	function appendNewFeeToDestinationWithoutTaxSpan(data)
	{
		// Fetch current and new SMS data
		var currentTotalDestinationsFee = parseFloat(jQuery("span#totalDestinationsFeeWithoutTax").text());
		var smsFee = parseFloat(jQuery("span#smsFee").text());
		var smsQuantity = parseFloat(jQuery("span#smsQuantity").text());
		var newSmsDestinationRequested = parseFloat(data.requested);
		var newTotalDestinationsFee = (smsFee * smsQuantity * newSmsDestinationRequested) + currentTotalDestinationsFee;
		
		// Fire!
		jQuery("span#totalDestinationsFeeWithoutTax").text(newTotalDestinationsFee);
	}
	
	// Push new destinations fee (with tax)
	function appendNewFeeToDestinationWithTaxSpan(data)
	{
		// Fetch current and new SMS data
		var currentTotalDestinationsFeeWithoutTax = parseFloat(jQuery("span#totalDestinationsFeeWithoutTax").text());
		var newTotalDestinationsFeeWithTax = currentTotalDestinationsFeeWithoutTax * 1.05;
		
		// Fire!
		jQuery("span#totalDestinationsFeeWithTax").text(newTotalDestinationsFeeWithTax);
	}
	// Ajax create destination
	jQuery(function($){
		jQuery("form#destinationForm").bind("submit", function(event){

			// Fetch form data
			var destinationFormValidity = jQuery('form#destinationForm').validationEngine('validate');			
			var destinationFormValue = jQuery("form#destinationForm").formSerialize();
			
			// Fire!
			if (destinationFormValidity)
			{
				// Craft ajax loader icon
				var ajaxIconLoader = "<img id='ajaxIconLoader' src='/images/misc/ajax-loader.gif' style='margin:0 10px; vertical-align: middle;'></img>";
				jQuery(ajaxIconLoader).appendTo(jQuery("input#destinationSubmit").parent());
			
				// Ajax
				jQuery.ajax({
					type: "POST",
					url: "/en_US/sms/order/ajax-create-destination/",
					data: destinationFormValue,
					success: function(data){
						var storedDestinationId = data;
						jQuery.ajax({
							type: "GET",
							url: "/en_US/sms/order/ajax-retrieve-destination/id/" + storedDestinationId,
							success: function(data){
								var storedDestinationData = data;
								appendNewDataToDestinationTable(storedDestinationData);
								appendNewDestinationQuantity(storedDestinationData);
								appendNewFeeToDestinationWithoutTaxSpan(storedDestinationData);
								appendNewFeeToDestinationWithTaxSpan(storedDestinationData);
								jQuery("img#ajaxIconLoader").fadeOut();
								jQuery("input#destination_value, input#dispatch_date, input#destination_start, input#destination_end").clearFields();
							}
						});
					}
				});
			}
			
			// Prevent default action
			event.preventDefault();
			return false;

		});
	});
</script>
<!----- Destination JavaScript End ----->

<!----- Transaction HTML Start ----->
<div class="twelve columns">
	<div class="panel" style="">
		<h4 class="hide-for-small"><?php echo $this->translate('Transaction'); ?><hr></h4>
		
		<!----- Transaction List Start ----->	
		<?php
			$confirmMessage = $this->translate('Are you sure to delete?');
			$language = $this->translate('/en_US');
			$deleteLink = $this->translate('/en_US') . "/sms/order/delete-transaction/id/";
			$updateLink = $this->translate('/en_US') . "/sms/order/update-transaction/id/";
		?>

		<table>
			<thead>
				<tr>			
					<th><?php echo $this->translate('ID') ?></th>
					<th><?php echo $this->translate('Order ID') ?></th>
					<th><?php echo $this->translate('Receipt Number') ?></th>
					<th><?php echo $this->translate('Bank Account') ?></th>
					<th><?php echo $this->translate('Deposit Date') ?></th>
					<th><?php echo $this->translate('Depositor Name') ?></th>
					<th><?php echo $this->translate('Deposit Fee') ?></th>
					<?php if (!$this->order['order_status']): ?>
						<th><?php echo $this->translate('Links') ?></th>
					<?php endif; ?>
				</tr>
			</thead>
			<tbody id="transactionTableBody">
		<?php if ($this->transactions): ?>
			<?php foreach ($this->transactions as $transactions): ?>
					<tr>
						<td>
							<?php echo $transactions['id']; ?>
						</td>
						<td>
							<?php echo $transactions['order_id']; ?>
						</td>
						<td>
							<?php echo $transactions['receipt_number']; ?>
						</td>
						<td>
							<?php echo $transactions['bank_account']; ?>
						</td>
						<td>
							<?php echo Melobit_Date_Convertor::timestamp_to_jalali($transactions['deposit_date']); ?>
						</td>
						<td>
							<?php echo $transactions['depositor_name']; ?>
						</td>
						<td>
							<?php echo $transactions['deposit_fee']; ?>
						</td>
						<?php if (!$this->order['order_status']): ?>
							<td>
							<a href="<?php echo $updateLink .  $transactions['id']; ?>">
								<img src="/images/misc/edit-icon-white-micro.png" style="margin: 0 10px; vertical-align: middle"></img>
							</a>
							<br/>
							<a href="<?php echo $deleteLink .  $transactions['id']; ?>" 
								onclick="return confirm('<?php echo $confirmMessage; ?>')">
								<img src="/images/misc/delete-icon-white-micro.png" style="margin: 0 10px; vertical-align: middle"></img>
							</a>
							</td>
						<?php endif; ?>
					</tr>
			<?php endforeach; ?>
		<?php endif; ?>
			</tbody>
		</table>
		<!----- Transaction List End -----> 

		<!----- Transaction Form Start ----->
		<?php if (!$this->order['order_status']): ?>
		<div class="panel">
			<div style="margin:10px 0 10px 10px">
				<img src="/images/misc/plus-icon-green-small.png" style="margin: 0 10px; vertical-align: middle">
					<a href="#" id="transactionFormToggle" style="vertical-align: middle"><?php echo $this->translate('Create a new Transaction'); ?></a>
				</img>
			</div>
			<?php echo $this->transactionForm; ?>
		</div>
		<?php endif; ?>
		<!----- Transaction Form End -----> 
		
	</div>
</div>
<!----- Transaction HTML End ----->

<!----- Transaction JavaScript Start ----->
<?php if (!$this->order['order_status']): ?>
<script type="text/javascript">
	// Calendar
	Calendar.setup({
		inputField				: "deposit_date",	// id of the input field
		displayArea			: "deposit_date", // id of displayArea field
		button						: "depositDateChooserImge",	// trigger for the calendar (button ID)
		ifFormat					: "%Y-%m-%d %H:%M",	// format of the input field
		showsTime				: true,
		dateType					: 'jalali',
		timeFormat				: "24",
		weekNumbers		: false,
        showOthers			: true,
		singleClick				: false,
		autoShowOnFocus	: false,
		langNumbers			: false,
	});
</script>
<?php endif; ?>

<script type="text/javascript">
	// Toggle transaction form
	jQuery("form#transactionForm").css("display", "none");
	jQuery(function($){		
		jQuery("a#transactionFormToggle").bind("click", function(event){
			jQuery("form#transactionForm").toggle("slow");				
			// Prevent default action
			event.preventDefault();
		});
	});
	
	// Push new transaction row
	function appendNewDataToTransactionTable(data)
	{
		var newTableRow = "<tr><td>" 
			+ data.id +"</td><td>"
			+ data.order_id +"</td><td>"
			+ data.receipt_number +"</td><td>"
			+ data.bank_account +"</td><td>"
			+ data.deposit_date +"</td><td>"
			+ data.depositor_name +"</td><td>"
			+ data.deposit_fee +"</td><td>"
			+ "<a href='<?php echo $updateLink ?>" + data.id + "'>"
			+ "<img src='/images/misc/edit-icon-white-micro.png' style='margin: 0 10px; vertical-align: middle'></img>"
			+ "</a>"
			+ "<br/>"
			+ "<a href='<?php echo $updateLink ?>" + data.id +  "'>"
			+ "<img src='/images/misc/delete-icon-white-micro.png' style='margin: 0 10px; vertical-align: middle'></img>"
			+ "</a>"
			+ "</td></tr>";		
		jQuery(newTableRow)
			.css({
			 "background":"#2BA6CB",
			 "display":"none"
			})
			.appendTo("tbody#transactionTableBody")
			.fadeIn("slow", function(){
				jQuery(this).css({
				    "display":""
				    });
				jQuery(this).animate({
				    backgroundColor:"#F9F9F9"
				    },
				    300,
				    function(){
				jQuery(this).css({
				    "background":""
				    });	
				});
			});  
	}

	// Push new transaction fee
	function appendNewFeeToTransactionSpan(data)
	{
		// Fetch current and new SMS data
		var currentTotalTransactionsFee = parseFloat(jQuery("span#totalTransactionsFee").text());
		var newTransactionFee = parseFloat(data.deposit_fee);
		var newTotalTransactionsFee = currentTotalTransactionsFee + newTransactionFee;
		
		// Fire!
		jQuery("span#totalTransactionsFee").text(newTotalTransactionsFee);
	}	
	
	// Ajax create transaction
	jQuery(function($){
		jQuery("form#transactionForm").bind("submit", function(event){

			// Fetch form data
			var transactionFormValidity = jQuery('form#transactionForm').validationEngine('validate');			
			var transactionFormValue = jQuery("form#transactionForm").formSerialize();
			
			// Fire!
			if (transactionFormValidity)
			{
				// Craft ajax loader icon
				var ajaxIconLoader = "<img id='ajaxIconLoader' src='/images/misc/ajax-loader.gif' style='margin:0 10px; vertical-align: middle;'></img>";
				jQuery(ajaxIconLoader).appendTo(jQuery("input#transactionSubmit").parent());
			
				// Ajax
				jQuery.ajax({
					type: "POST",
					url: "/en_US/sms/order/ajax-create-transaction/",
					data: transactionFormValue,
					success: function(data){
						var storedTransactionId = data;
						jQuery.ajax({
							type: "GET",
							url: "/en_US/sms/order/ajax-retrieve-transaction/id/" + storedTransactionId,
							success: function(data){
								var storedTransactionData = data;
								appendNewDataToTransactionTable(storedTransactionData);
								appendNewFeeToTransactionSpan(storedTransactionData);
								jQuery("img#ajaxIconLoader").fadeOut();
								jQuery("form#transactionForm").clearForm();
							}
						});
					}
				});
			}
			
			// Prevent default action
			event.preventDefault();
			return false;

		});
	});
</script>
<!----- Transaction JavaScript End ----->