<?php $this->layout()->setLayout('page'); ?>
	
<h4><?php echo $this->translate('Destination Status'); ?></h4><br />
<table>
	<thead>
		<tr>
			<th><?php echo $this->translate('GetStatusResult') ?></th>
			<th><?php echo $this->translate('Status') ?></th>
			<th><?php echo $this->translate('Delivered') ?></th>
			<th><?php echo $this->translate('Sent') ?></th>
		</tr>
	</thead>
	<tbody>
		<td><?php echo $this->status->GetStatusResult; ?></td>
		<td><?php echo $this->status->status; ?></td>
		<td><?php echo $this->status->delivered; ?></td>
		<td><?php echo $this->status->sent; ?></td>
	</tbody>
</table>
	
<h4><?php echo $this->translate('Destination Information'); ?></h4><br />
<table>
	<thead>
		<tr>
			<th><?php echo $this->translate('Destination ID') ?></th>
			<th><?php echo $this->translate('Order ID') ?></th>
			<th><?php echo $this->translate('Bulk ID') ?></th>
			<th><?php echo $this->translate('Destination Type') ?></th>
			<th><?php echo $this->translate('Destination Value') ?></th>
			<th><?php echo $this->translate('Dispatch Date') ?></th>
			<th><?php echo $this->translate('Quantity') ?></th>
			<th><?php echo $this->translate('Requested') ?></th>
		</tr>
	</thead>
	<tbody>
		<td><?php echo $this->destination->id; ?></td>
		<td><?php echo $this->destination->order_id; ?></td>
		<td><?php echo $this->destination->bulk_id; ?></td>
		<td><?php echo $this->destination->destination_type; ?></td>
		<td><?php echo $this->destination->destination_value; ?></td>
		<td><?php echo Melobit_Date_Convertor::timestamp_to_jalali($this->destination->dispatch_date); ?></td>
		<td><?php echo $this->destination->destinations_quantity; ?></td>
		<td><?php echo ($this->destination->destination_end - $this->destination->destination_start); ?></td>

	</tbody>
</table>






