<?php $this->layout()->setLayout('page'); ?>

<h3><?php echo $this->translate('List of Dispatch'); ?></h3><br />

<?php if (!$this->orders): ?>
<p><?php echo $this->translate('There is no order!'); ?></p>
<?php else: ?>

<?php
	$confirmMessage = $this->translate('Are you sure to delete?');
?>

<table>
	<thead>
		<tr>
			<th><?php echo $this->translate('ID') ?></th>
			<th><?php echo $this->translate('Customer Name') ?></th>
			<th><?php echo $this->translate('Orderer Username') ?></th>
			<th><?php echo $this->translate('Order Date') ?></th>
			<!--<th><?php // echo $this->translate('SMS Content') ?></th>-->
			<th><?php echo $this->translate('Test Phone') ?></th>
			<th><?php echo $this->translate('Order Status') ?></th>
			<th><?php echo $this->translate('Control Status') ?></th>
			<th><?php echo $this->translate('Dispatch Status') ?></th>
			<th><?php echo $this->translate('Links') ?></th>
		</tr>
	</thead>
	<tbody>
<?php foreach ($this->orders as $order): ?>
		<tr>
			<td>
				<?php echo $order['id']; ?>
			</td>
			<td>
				<?php $customerName = Sms_Model_CustomerModel::listCustomer($order['customer_id']);?>
				<?php echo $customerName['first_name'] . ' ' .  $customerName['last_name']; ?>
			</td>
			<td>
				<?php $ordererUsername = Model_UserModel::getUsers($order['user_id']);?>
				<?php echo $ordererUsername['username']; ?>
			</td>
			<td>
				<?php echo Melobit_Date_Convertor::timestamp_to_jalali($order['order_date']); ?>
			</td>
			<!--
			<td>
				<?php // echo $order['sms_content']; ?>
			</td>
			-->
			<td>
				<?php echo $order['test_phone']; ?>
			</td>
			<td>
				<?php echo $order['order_status']; ?>
			</td>
			<td>
				<?php echo $order['control_status']; ?>
			</td>
			<td>
				<?php echo $order['dispatch_status']; ?>
			</td>
			<td>
				<a href="<?php echo $this->translate('/en_US');?>/sms/dispatch/review-dispatch/id/<?php echo $order['id']; ?>">
					<?php echo $this->translate('Review') ?></a>
			</td>
		</tr>
<?php endforeach; ?>
	</tbody>
</table>

<?php endif; ?>

<p><a href="<?php echo $this->translate('/en_US'); ?>
	/sms/order/create-order"><?php echo $this->translate('Create a new order'); ?></a></p>
	
