<?php $this->layout()->setLayout('page'); ?>

<ul>
	<li>
		<a href="<?php echo $this->translate('/en_US'); ?>
			/sms/company/"><?php echo $this->translate('List of Companies'); ?></a>
	</li>
	<li>
		<a href="<?php echo $this->translate('/en_US'); ?>
			/sms/customer/"><?php echo $this->translate('List of Customers'); ?></a>
	</li>
	<li>
		<a href="<?php echo $this->translate('/en_US'); ?>
			/sms/order/"><?php echo $this->translate('List of Orders'); ?></a>
	</li>
</ul>
