<?php $this->layout()->setLayout('page'); ?>

<?php
	// determine which language displays
	$page_headline = 'page_headline_' . $this->translate('en');
	$page_description = 'page_description_' . $this->translate('en');
?>
<h3><?php echo $this->translate('Search Results'); ?></h3>
<?php if(is_array($this->results) && count($this->results) > 0) { ?>
<p><?php echo $this->translate('Your search for'); ?> 
	<strong><?php echo $this->keywords; ?></strong> 
		<?php echo $this->translate('returned'); ?>
			<?php echo count($this->results); ?> 
				<?php echo $this->translate('result(s)'); ?>.</p>
	<?php foreach($this->results as $result) { ?>
	<h3><a href="<?php echo $this->translate('/en_US');?>/pages/<?php echo $result->page_id; ?>/<?php echo $result->page_name; ?>">
		<?php echo $result->$page_headline; ?>
	</a></h3>
	<p><?php echo $result->$page_description; ?></p>
	<?php }} else { ?>
	<p><?php echo $this->translate('Your search for'); ?> 
		<strong><?php echo $this->keywords; ?></strong> 
			<?php echo $this->translate('did not return any results'); ?>.</p>
<?php } ?>

