<?php $this->layout()->setLayout('page'); ?>

<h3><?php echo $this->translate('My Account'); ?></h3>
<?php 
	if ($this->identity == null)
	{
?>
<p><?php echo $this->translate('To log in'); ?> <a href="/user/login">
	<?php echo $this->translate('click here'); ?></a></p>
<?php
	}
	else
	{
?>
<p>
	<?php echo $this->translate('Hello!'); ?> <strong><?php echo $this->identity->first_name; ?></strong>,
	<br/>
	<?php echo $this->translate('Your role is:'); ?> <em><?php echo $this->identity->role; ?></em>
</p>
<p><?php echo $this->translate('To log out'); ?> 
	<a href="<?php echo $this->translate('/en_US'); ?>/default/user/logout">
	<?php echo $this->translate('click here'); ?></a></p>
<?php
	}
?>
