<?php $this->layout()->setLayout('page'); ?>

<h3><?php echo $this->translate('Current Users'); ?></h3>
<?php
	if ($this->users != null)
	{
?>
	<table>
		<thead>
			<tr>
				<th><?php echo $this->translate('Links'); ?></th>
				<th><?php echo $this->translate('Last Name'); ?></th>
				<th><?php echo $this->translate('First Name'); ?></th>
				<th><?php echo $this->translate('Username'); ?></th>
				<th><?php echo $this->translate('Role'); ?></th>
			</tr>
		</thead>
		<tbody>
			<?php echo $this->partialLoop('partials/_user-row.phtml', $this->users); ?>
		</tbody>
	</table>
<?php
	}
	else
	{
?>
<p><?php echo $this->translate('You do not have any users yet.'); ?></p>
<?php
	}
?>
<p><a href="<?php echo $this->translate('/en_US'); ?>
	/default/user/create"><?php echo $this->translate('Create a new user'); ?></a></p>
