<?php $this->layout()->setLayout('page'); ?>

<h3>Current Users</h3>
<?php
	if ($this->users != null)
	{
?>
	<table>
		<thead>
			<tr>
				<th>Links</th>
				<th>Last Name</th>
				<th>First Name</th>
				<th>Username</th>
				<th>Role</th>
			</tr>
		</thead>
		<tbody>
			<?php echo $this->partialLoop('partials/_user-row.phtml', $this->users); ?>
		</tbody>
	</table>
<?php
	}
	else
	{
?>
<p>You do not have any users yet.</p>
<?php
	}
?>
<p><a href="/user/create">Create a new user</a></p>
