<?php $this->layout()->setLayout('page'); ?>

<?php if ($this->identity == null) { ?>

      <ul class="right">
        <li><a href="<?php echo $this->translate('/en_US');?>/default/user/login">
        	<?php echo $this->translate('Sing in'); ?></a></li>
      </ul>

<?php }	else { ?>

      <!-- Right Nav Section -->
      <ul class="right">
        <li class="has-dropdown">
          <a href="#"><?php echo $this->translate('Hi,') . ' ' . $this->identity->first_name; ?></a>
          <ul class="dropdown">
						<li><label><?php echo $this->translate($this->identity->role); ?></label></li>
            <li><a href="<?php echo $this->translate('/en_US');?>/default/user/update/id/
					<?php echo $this->identity->id; ?>">
            		<?php echo $this->translate('Profile');?></a></li>
            <li><a href="<?php echo $this->translate('/en_US');?>/default/admin/">
            	<?php echo $this->translate('Setting');?></a></li>
            <li><a href="#"><?php echo $this->translate('Tasks');?></a></li>
            <li class="divider"></li>
            <li><a href="<?php echo $this->translate('/en_US');?>/default/user/logout">
            	<?php echo $this->translate('Sign out');?></a></li>
          </ul>
        </li>
        <li class="divider"></li>
        <li><a href="#"><i class="medIcon foundicon-smiley"></i></a></li>
        <li class="divider"></li>
      </ul>
      
<?php } ?>

