<?php
	if ($this->page_id > 0)
	{
		$page = new Melobit_Content_Item_Page($this->page_id);
		$pageName = $page->name;
	}
	else
	{
		$pageName = null;
	}
?>

<tr>
	<td class="links">
		<a href="/menu/edit/id/<?php echo $this->id; ?>">Update</a> | 
		<a href="/menu/move/direction/down/id/<?php echo $this->id; ?>">Move down</a> | 
		<a href="/menu/move/direction/up/id/<?php echo $this->id; ?>">Move up</a> | 
		<a href="/menu-item/list/menu/<?php echo $this->id; ?>">Manage Menu Items</a> | 
		<a href="/menu/delete/id/<?php echo $this->id; ?>" 
			onclick="return confirm('Are you sure to delete?')">Delete</a>
	</td>
	<td><?php echo $this->name; ?></td>
	<td><?php echo $pageName; ?></td>
	<td><?php echo $this->link; ?></td>
	<td><?php echo $this->access_level; ?></td>
</tr>
