<?php
	$confirmMessage = $this->translate('Are you sure to delete?');
?>

<tr>
	<td class="links">
		<a href="<?php echo $this->translate('/en_US');?>/default/user/update/id/<?php echo $this->id; ?>">
			<?php echo $this->translate('Update'); ?></a> | 
		<a href="<?php echo $this->translate('/en_US');?>/default/user/delete/id/<?php echo $this->id; ?>" 
		onclick="return confirm('<?php echo $confirmMessage; ?>')">
			<?php echo $this->translate('Delete'); ?></a>
	</td>
	<td><?php echo $this->last_name; ?></td>
	<td><?php echo $this->first_name; ?></td>
	<td><?php echo $this->username; ?></td>
	<td><?php echo $this->role; ?></td>
</tr>
