<?php $this->layout()->setLayout('page'); ?>

<h3><?php echo $this->translate('Manage Menu Items'); ?></h3>
<p><?php echo $this->translate('Current Menu:'); ?><?php echo ' ' . $this->menu->name; ?></p>

<?php if ($this->items != null) { ?>
<table>
	<thead>
		<tr>
			<th><?php echo $this->translate('Links'); ?></th>
			<th><?php echo $this->translate('Label'); ?></th>
			<th><?php echo $this->translate('Page'); ?></th>
			<th><?php echo $this->translate('Link'); ?></th>
		</tr>
	<thead>
	<tbody>
		<?php echo $this->partialLoop('partials/_menu-item-row.phtml', $this->items); ?>
	</tbody>
</table>
<?php } else { ?>
<p><?php echo $this->translate('This menu does not have any items yet.'); ?></p>
<?php } ?>

<p><a href="<?php echo $this->translate('/en_US');?>/default/menu-item/add/menu/
	<?php echo $this->menu->id; ?>"><?php echo $this->translate('Add a new item'); ?></a></p>
