
  <!-- Footer -->

  <footer class="row">
    <div class="twelve columns">
      <hr />
      <div class="row">
        <div class="nine columns">
        	<p>
				<a href="/"><?php echo $this->siteTitle; ?></a> | 
				<a href="/page/open/id/4/title/melobit-gpl-version-2-license">License / GPLv2</a>
			</p>
        </div>
        <div class="three columns text-right">
        	<p>
        		<a href="/contact">Contact</a> |
				<a href="/bug/create">Report Bugs</a>
			</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- End Footer -->  

	<!-- jQuery Validation Engine -->
	<link rel="stylesheet" type="text/css" href="/javascripts/jQuery-validationEngine-2.6.1/css/validationEngine.jquery.css" />
	<script type="text/javascript" src="/javascripts/jQuery-validationEngine-2.6.1/js/jquery-1.7.2.min.js"></script>
	<script type="text/javascript" src="/javascripts/jQuery-validationEngine-2.6.1/js/languages/jquery.validationEngine-en.js"></script>
	<script type="text/javascript" src="/javascripts/jQuery-validationEngine-2.6.1/js/jquery.validationEngine.js"></script>
	<script type="text/javascript">
	  $(document).ready(function() {

		$('.jQueryValidation').validationEngine();
	  });
	</script>
	<!-- End jQuery Validation Engine -->

  <!-- Included JS Files (Uncompressed) -->
  <!--
  <script src="/skins/foundation/javascripts/jquery.js"></script>
  <script src="/skins/foundation/javascripts/jquery.foundation.mediaQueryToggle.js"></script>
  <script src="/skins/foundation/javascripts/jquery.foundation.forms.js"></script>
  <script src="/skins/foundation/javascripts/jquery.foundation.reveal.js"></script>
  <script src="/skins/foundation/javascripts/jquery.foundation.orbit.js"></script>
  <script src="/skins/foundation/javascripts/jquery.foundation.navigation.js"></script>
  <script src="/skins/foundation/javascripts/jquery.foundation.buttons.js"></script>
  <script src="/skins/foundation/javascripts/jquery.foundation.tabs.js"></script>
  <script src="/skins/foundation/javascripts/jquery.foundation.tooltips.js"></script>
  <script src="/skins/foundation/javascripts/jquery.foundation.accordion.js"></script>
  <script src="/skins/foundation/javascripts/jquery.foundation.alerts.js"></script> -->
  <script src="/skins/foundation/javascripts/jquery.placeholder.js"></script>
  <script src="/skins/foundation/javascripts/jquery.foundation.topbar.js"></script>
  
  
  <!-- Included JS Files (Compressed) -->
  <!--
  <script src="/skins/foundation/javascripts/jquery.js"></script>
  <script src="/skins/foundation/javascripts/foundation.min.js"></script>
  -->
  
  <!-- Initialize JS Plugins -->
  <script src="/skins/foundation/javascripts/app.js"></script>

	<!-- TinyMCE -->
	<script type="text/javascript" src="/javascripts/tinymce-3.5.7/jscripts/tiny_mce/tiny_mce.js"></script>
	<script type="text/javascript">
		tinyMCE.init({
			mode : "specific_textareas",
			theme : "advanced",
			skin : "o2k7",
		    editor_selector : "withEditor",
		    editor_deselector : "withoutEditor",
			relative_urls : false,
			plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,inlinepopups,autosave",

			// Theme options
			theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
			theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
			theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
			theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,restoredraft",
			theme_advanced_toolbar_location : "top",
			theme_advanced_toolbar_align : "left",
			theme_advanced_statusbar_location : "bottom",
			theme_advanced_resizing : true,
		});
	</script>
	<!-- End TinyMCE -->
	
  <!-- Database Profiler (only in DEVELOPMENT environment) -->
  
  <div class="row">
    <div class="twelve columns">
		<?php echo $this->profiler; ?>
    </div>
  </div>

  <!-- End Database Profiler (only in DEVELOPMENT environment) -->

</body>
</html>
