
  <!-- First Band (Slider) -->
  <!-- The Orbit slider is initialized at the bottom of the page by calling .orbit() on #slider -->
    
  <div class="row">
    <div class="eight columns">
        <img class="siteBanner" src="/images/misc/index_banner.jpg" />
	</div>
    <div class="four columns">
      <h4>What is MeloBit?</h4>
      	<p class="siteDescription">
      	MeloBit is a free and open source Content Management System (CMS) by which you can easily 
      	build an enterprise web site or even a weblog. Give it a try:
      	</p>
      	<p>
      		<br />
		  	<a class="small radius button">Download in GitHub</a> 
		  	<a class="small radius button secondary">Look inside!</a>
      	</p>
    </div>
    <hr />
  </div>
  
  <!-- End First Band (Slider) -->

  <!-- Three-up Content Blocks -->
  
  <div class="row">
  
    <div class="four columns">
      <div class="text-center">
      	<i class="ligther largIcon foundicon-idea"></i>
      	<h4>Developers</h4>
      </div>
      	<p>MeloBit back-end is written in <a href="http://www.php.net">
      	PHP</a>, based on <a href="http://www.Zend.com">Zend</a> Framework. 
      	Choosing Database for Melobit is a matter of taste, because Melobit support all of them, 
      	such as <a href="http://www.mysql.com/">MySQL</a>, <a href="http://www.sqlite.org">SQLite</a>, 
      	<a href="http://www.oracle.com/us/products/database/overview/">Oracle</a> or even an XML file as database.</p>
      	<p class="text-right">
      	<a href="http://www.melobit.com/page/open/id/7/title/how-to-create-modules-for-melobit">More ...</a></p>
    </div>
    
    <div class="four columns">
      <div class="text-center">
      	<i class="ligther largIcon foundicon-website"></i>
      	<h4>Designers</h4>
      </div>
      	<p>MeloBit template engine is based on <a href="http://foundation.zurb.com">Foundation</a> Framework  
      	which is a simple, powerful and responsive (Multi-Device) front-end Framework. 
      	So creating template for MeloBit is as easy as pie.</p>
      	<p class="text-right">
      	<a href="http://www.melobit.com/page/open/id/6/title/how-to-create-skins-for-melobit">More ...</a></p>
    </div>
    
    <div class="four columns">
      <div class="text-center">
      	<i class="ligther largIcon foundicon-edit"></i>
      	<h4>Site Authors</h4>
      </div>
		<p>When your website is built with MeloBit, you easily change content from anywhere.
		It doesn't matter that you are using your tablet, PC or mobile, because Melobit has Cross-Browser 
		and Multi-Device support.</p>
      	<p class="text-right">
      	<a href="http://www.melobit.com/page/open/id/5/title/how-to-install-melobit">More ...</a></p>
    </div>
    
  </div>
  
  <!-- End Three-up Content Blocks -->

  <!-- Content -->

      <div class="row">
        <div class="twelve columns">
          <div class="panel">
            <h3>Get involved</h3>
            <blockquote>
            If you are interested to get involved in extending MeloBit, We propose to go in this direction:
            </blockquote>
            
			  <div class="row">
				<div class="two columns text-center">
				  <a href="http://www.amazon.com/The-Object-Oriented-Thought-Process-Edition/dp/0672330164/ref=sr_1_1?ie=UTF8&qid=1351252375&sr=8-1&keywords=The+Object+Oriented+Thought+Process" class="th">
				  <img class="centerThing" src="/images/misc/book_1.png" /></a>		      
				  <p><a href="http://www.amazon.com/The-Object-Oriented-Thought-Process-Edition/dp/0672330164/ref=sr_1_1?ie=UTF8&qid=1351252375&sr=8-1&keywords=The+Object+Oriented+Thought+Process" class="th">The Object Oriented Thought Process</a></p>
				</div>
				<div class="two columns text-center">
				  <a href="http://www.amazon.com/Beginning-PHP-MySQL-Professional-Development/dp/1430231149/ref=sr_1_1?ie=UTF8&qid=1351252460&sr=8-1&keywords=PHP+and+MySQL+From+Novice+to+Professional" class="th">
				  <img class="centerThing" src="/images/misc/book_2.png" /></a>		      
				  <p><a href="http://www.amazon.com/Beginning-PHP-MySQL-Professional-Development/dp/1430231149/ref=sr_1_1?ie=UTF8&qid=1351252460&sr=8-1&keywords=PHP+and+MySQL+From+Novice+to+Professional" class="th">PHP and MySQL From Novice to Professional</a></p>
				</div>
				<div class="two columns text-center">
				  <a href="http://www.amazon.com/JavaScript-Good-Parts-Douglas-Crockford/dp/0596517742/ref=sr_1_1?ie=UTF8&qid=1351252605&sr=8-1&keywords=JavaScript+the+Good+Parts" class="th"><img class="centerThing" src="/images/misc/book_3.png" /></a>		      
				  <p><a href="http://www.amazon.com/JavaScript-Good-Parts-Douglas-Crockford/dp/0596517742/ref=sr_1_1?ie=UTF8&qid=1351252605&sr=8-1&keywords=JavaScript+the+Good+Parts" class="th">JavaScript the Good Parts</a></p>
				</div>
				<div class="two columns text-center">
				  <a href="http://www.amazon.com/Zend-Framework-A-Beginners-Guide/dp/007163939X/ref=sr_1_1?ie=UTF8&qid=1351252695&sr=8-1&keywords=Zend+Framework%3B+A+Beginners+Guide" class="th"><img class="centerThing" src="/images/misc/book_4.png" /></a>		      
				  <p><a href="http://www.amazon.com/Zend-Framework-A-Beginners-Guide/dp/007163939X/ref=sr_1_1?ie=UTF8&qid=1351252695&sr=8-1&keywords=Zend+Framework%3B+A+Beginners+Guide" class="th">Zend Framework; A Beginners Guide</a></p>
				</div>
				<div class="two columns text-center">
				  <a href="http://www.amazon.com/Zend-Framework-Action-Rob-Allen/dp/1933988320/ref=sr_1_1?ie=UTF8&qid=1351252759&sr=8-1&keywords=Zend+Framework+in+Action" class="th"><img class="centerThing" src="/images/misc/book_5.png" /></a>		      
				  <p><a href="http://www.amazon.com/Zend-Framework-Action-Rob-Allen/dp/1933988320/ref=sr_1_1?ie=UTF8&qid=1351252759&sr=8-1&keywords=Zend+Framework+in+Action" class="th">Zend Framework in Action</a></p>
				</div>
				<div class="two columns text-center">
				  <a href="http://www.amazon.com/Pro-Zend-Framework-Techniques-Project/dp/1430218797/ref=sr_1_1?ie=UTF8&qid=1351252800&sr=8-1&keywords=Pro+Zend+Framework+Techniques" class="th"><img class="centerThing" src="/images/misc/book_6.png" /></a>		      
				  <p><a href="http://www.amazon.com/Pro-Zend-Framework-Techniques-Project/dp/1430218797/ref=sr_1_1?ie=UTF8&qid=1351252800&sr=8-1&keywords=Pro+Zend+Framework+Techniques" class="th">Pro Zend Framework Techniques</a></p>
				</div>
		      </div>  
		      
		     <p>
		     Based on your previous knowledge, each of these books can significantly help you in the way of
		     being a Professional Web Developer. 
		     MeloBit developers team also used this way, so at the end of this way you can be a part of us.   
		     </p>          
            
          </div>
        </div>	
      </div>
      
  <!-- End Content -->

